name: Build docker images on release

on:
  release:
    types: [created]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        name: Log in to the Container registry
        with:
          registry: ${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER}}
          username: ${{ secrets.EO_PROJ_DOCKER_USERNAME }}
          password: ${{ secrets.EO_PROJ_DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
        id: buildx
      - uses: docker/build-push-action@v4
        name: Build and push Docker image
        with:
          context: .
          file: Dockerfile
          cache-from: type=registry,ref=${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER }}/stac-fastapi-pgstac:cache
          cache-to: type=registry,ref=${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER }}/stac-fastapi-pgstac:cache,mode=max
          push: true
          tags: ${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER }}/stac-fastapi-pgstac:${{ github.event.release.tag_name }}


  docker-build-push-prod-init-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set Short SHA
        run: echo "SHORT_SHA=$(git rev-parse --short=7 $GITHUB_SHA)" >> $GITHUB_ENV
      - name: echo Short SHA
        run: echo $SHORT_SHA
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER}}
          username: ${{ secrets.EO_PROJ_DOCKER_USERNAME }}
          password: ${{ secrets.EO_PROJ_DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile-init.custom
          cache-from: type=registry,ref=${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER }}/stac-fastapi-pgstac-init-image:cache
          cache-to: type=registry,ref=${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER }}/stac-fastapi-pgstac-init-image:cache,mode=max
          push: true
          tags: ${{ secrets.EO_PROJ_DOCKER_LOGIN_SERVER }}/stac-fastapi-pgstac-init-image:${{ github.event.release.tag_name }}

